version: '3.1'

services:
  db_mysql:
    container_name: db_mysql
    image: mysql
    ports:
      - "3307:3306"
    restart: always
    environment:
      MYSQL_USER: andre
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - /var/lib/mysqld:/var/lib/mysql
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - "8091:80"
    environment:
      - PMA_HOST=db_mysql
    depends_on:
      - db_mysql