spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/follow-improve
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
      database-platform: org.hibernate.dialect.MySQL8Dialect
  flyway:
    table: flyway_schema_history
    sql-migration-prefix: V
    sql-migration-suffix: .sql
    group: true
    location: classpath:db/migration


